### ISSUE TITLE
 Can I import a local xml style file with r2cytoscape?

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/RCy3#1]
From Kozo:

> I'm trying to import a local Style XML file with r2cytoscape.
> 
> As far as I saw https://github.com/cytoscape/r2cytoscape/tree/master/R ,
> I thought that the function was not implemented yet.
> Is this right? If it is so, Is there anything I can support you?

**Comment by AlexanderPico** [comment]
Good question! I don't see any support for this function in CyREST or commands... so we can't add it to the R library yet.

David or Scooter: any plans to add this to CyREST and/or commands?

**Comment by dotasek** [comment]
There isn't an XML way to do this, but there's import-export functionality for JSON via these endpoints:

**Comment by kozo2** [comment]
Thanks for the info.
I will try json instead of XML.
