### ISSUE TITLE
The images are not appearing in the Cancer Network and Data vignette

### ISSUE THREAD

**Issue by jeffreyblanchard** [cytoscape/RCy3#102]
Thanks for putting this package together. Just a note to let you know that the images are not appearing in the Cancer Network and Data vignette. Take Care, Jeff

**Comment by AlexanderPico** [comment]
The Rmd is produced as an html here: https://cytoscape.org/cytoscape-automation/for-scripters/R/notebooks/Cancer-networks-and-data.nb.html

Can you point to where they are not showing up? Perhaps you mean while you are running the Rmd yourself? I don't think it was designed to work that way. If you have suggested edits to add them, please submit a PR. Thanks!

**Comment by jeffreyblanchard** [comment]
Hi Alexander,

What you just sent looks fine.  When in R

browsevignettes("RCy3)

If I click on the html.

Take Care, Jeff

**Comment by AlexanderPico** [comment]
Ah, got it.  I see it now. Looking into a fix...

Bioconductor has their own build system. I only provide the Rmd and the rest comes from them... and they don't have Cytoscape installed in their build rigs :) 

HOWEVER, [looking deeper](https://www.bioconductor.org/developers/package-guidelines/#vignettes), it seems like I can provide images along with my Rmd files. I'll give that a try in the next release!
