### ISSUE TITLE
Check name/SUID input support and documentation

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/RCy3#103]
Re: https://github.com/cytoscape/py4cytoscape/issues/37

Go through all functions and check support for accepting node/edge/network names and SUIDs, lists and singletons, and corresponding docs.

**Comment by bdemchak** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Check name/SUID input support and documentation #103](https://trello.com/c/QaOORs5Z/24-check-name-suid-input-support-and-documentation-103)
