### ISSUE TITLE
Convert tibbles to dataframes in createNetworkFromDataframes

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/RCy3#106]
Function should work if input objects are tibbles. Check for other functions with dataframe inputs as well.

**Comment by bdemchak** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Convert tibbles to dataframes in createNetworkFromDataframes #106](https://trello.com/c/bUuqUpLd/25-convert-tibbles-to-dataframes-in-createnetworkfromdataframes-106)

**Comment by AlexanderPico** [comment]
Works fine!

https://github.com/cytoscape/RCy3/blob/master/R/Networks.R#L923
