### ISSUE TITLE
commandsPOST() does not correctly parse arguments

### ISSUE THREAD

**Issue by mikekucera** [cytoscape/RCy3#136]
Originally reported here: https://github.com/BaderLab/EnrichmentMapApp/issues/463

The following command, which works in the Command panel, does not work correctly from RCy3...

`commandsPOST("enrichmentmap dataset color colors=\"enrichments_A=#440000\"")`

The output looks like this...

```
url=http://localhost:1234/v1/commands/enrichmentmap/dataset%20color
 body={
 "colors": "",
"enrichments_A": "#440000" 
}
```

It should probably look like this...

```
url=http://localhost:1234/v1/commands/enrichmentmap/dataset%20color
 body={
 "colors": "enrichments_A=#440000" 
}
```

Note, I can get it to work by using commandsRun() and URL encoding all the special characters, but that is not ideal.

`commandsRun("enrichmentmap dataset color colors=\"enrichments_A%3D%23AA0000\"")`

**Comment by rosscm** [comment]
Hi, I'm just wondering if there's been any development with this bug? Thanks

**Comment by rosscm** [comment]
Thanks @AlexanderPico, I'll use your solution.
