### ISSUE TITLE
Cytoscape Rmd notebooks broken in README

### ISSUE THREAD

**Issue by wptmdoorn** [cytoscape/RCy3#142]
Hi everyone,

First of all - thanks for this brilliant library. I noticed that the hyperlink 'Cytoscape Rmd notebooks' under 'Getting Started' in the README.MD is broken, which redirects to the URL:

https://cytoscape.org/cytoscape-automation/for-scripters/R/notebooks/

Strangely, accessing one of the individual notebooks does actually work (e.g., see below):

https://cytoscape.org/cytoscape-automation/for-scripters/R/notebooks/Overview-of-RCy3.nb.html

Thanks a lot.

Best wishes, William van Doorn

**Comment by AlexanderPico** [comment]
Thanks for letting us know! It's fixed now.
