### ISSUE TITLE
Annotation commands failing

### ISSUE THREAD

**Issue by ejurga** [cytoscape/RCy3#147]
Annotation commands addAnnotationText(), getAnnotationList(), and deleteAnnoation() are failing with the following error: 

Error: Failed to find command namespace: 'annotation'

Apparently, there is no annotation namespace in the cyREST API, even though my cyREST version is 3.11.1, which appears to be the most recent version. 

Running the command 'http://127.0.0.1:1234/v1/commands/' directly in the browser gives me a list of available namespaces, but 'annotation' is not among them. 

Not sure what is happening here...

**Comment by bdemchak** [comment]
Not sure what's going on here.

If I use Swagger (CyREST Command API) in Cytoscape 3.9.0-Beta1, I do see the Annotation namespace. I can use Swagger to perform an Annotation List operation successfully.

Could the problem be the Cytoscape version? Here is the 3.9.0-Beta1: https://cytoscape-builds.ucsd.edu/cytoscape-builds/Cytoscape-3.9.0/beta1/

**Comment by AlexanderPico** [comment]
That's my guess as well. These annotation commands are part of the development release of RCy3 and will be released in Cytoscape 3.9 in the coming weeks. If you are using the current release of Cytoscape, v3.8.2, you won't see any annotation commands.

Feel free to try the 3.9 beta linked to above, but be aware that this is a beta release.

**Comment by ejurga** [comment]
This was indeed the issue. With the beta release of v3.9, I can now add the annotations! 

Thanks for the help!
