### ISSUE TITLE
Functions to add

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/RCy3#15]
**Tools**
- ~~merge _-- pending command support and core app status_~~
- ~~network analyzer _-- pending command support and core app status_~~
- getCurrentStyle _-- [pending command support](https://cytoscape.atlassian.net/browse/CYTOSCAPE-12503)_

**Layout**
- ~~clearEdgeBends _-- [pending command support](https://github.com/cytoscape/cyREST/issues/92)_~~

**Comment by AlexanderPico** [comment]
User request:  show expression values on top of the nodes as bar charts

**Comment by risserlin** [comment]
getNetworkNames or getAllNetworkNames- returns all network names in the current session alternatively existsNetworkName.  I just need a way to easily test the new network name before assigning it. 
Thanks, 
Ruth

**Comment by AlexanderPico** [comment]
Thanks Ruth! I've passed these requests up to CyREST. I'll try to get these into RCy3 before the Oct Bioconductor release, if possible.

**Comment by risserlin** [comment]
Hi Alex, 
Do you have an example similar to your above examples of how to create a pie chart using RCy3?
Thanks, 
Ruth

**Comment by AlexanderPico** [comment]
Even better. There are new methods the latest dev version (to be released tomorrow):

- setNodeCustomBarChart
- setNodeCustomBoxChart
- setNodeCustomHeatMapChart
- **setNodeCustomPieChart**
- setNodeCustomRingChart

**Comment by lorenzoFabbri** [comment]
> **Tools**
> 
> * merge _-- pending command support_
> * network analyzer _-- pending command support_
> 
> **Layout**
> 
> * clearEdgeBends _--pending command support_

Is there any news regarding the `merge` functionality? I need to take the union of many networks and doing that by hand would be excruciating.

**Comment by AlexanderPico** [comment]
I’m holding my breath too. There’s nothing I can do in the R package until the merge tool is supported by CyREST (via either commands or CyREST directly). I will propagate it to RCy3 once it’s possible.

**Comment by AlexanderPico** [comment]
To be supported (finally) in Cytoscape 3.8 and this next release of RCy3:

- mergeNetworks
- analyzeNetwork
