### ISSUE TITLE
installApp() method gives a success message even if the app was not loaded

### ISSUE THREAD

**Issue by khanspers** [cytoscape/RCy3#161]
installApp() method gives a success message even if the app was not installed, for example if the app name was mistyped. To try, run 

installApp("largestSubnetwork")

which should fail (should be installApp("Largest Subnetwork"))

**Comment by AlexanderPico** [comment]
This is a CyCommands bug since the command returns the same success message for `apps install app=“blah”. RCy3 can’t know the difference.

**Comment by AlexanderPico** [comment]
I'll file in Jira.
