### ISSUE TITLE
setNodeBorderWidthMapping doesn't work as expected for setting a stepped gradient with two data points

### ISSUE THREAD

**Issue by khanspers** [cytoscape/RCy3#162]
Using setNodeBorderWidthMapping, it's not possible to create a mapping to define a "stepped" continuous mapping with anything under a certain value (for example 0.05) having a thicker border, and everything above is using the default. The attached screenshot shows what it should look like.

Here's the command: 
setNodeBorderWidthMapping('gal80Rsig',c(0,0.05),c(4,4),style.name="galFiltered Style")

This actually sets border width for all nodes to 4, instead of only those under 0.05. 

![Screen Shot 2021-11-09 at 3 05 03 PM](https://user-images.githubusercontent.com/1442197/141019853-1f9223b8-0a46-49ca-b1a0-f71c0d746896.png)

**Comment by AlexanderPico** [comment]
So, I just made this mapping using the Style GUI and it worked fine.

**Comment by AlexanderPico** [comment]
Huh. Okay, it seems to take n+2 args to set the "below min" and "above max" values. So, this works by automation:

setNodeBorderWidthMapping('gal80Rsig',c(0,0.05),c(4,4,4,2),style.name="galFiltered Style")
 #note: setting "above max" to 2
