### ISSUE TITLE
commandsRun('string show enrichment') doesn't work as part of a code chunk

### ISSUE THREAD

**Issue by khanspers** [cytoscape/RCy3#163]
In this Rmd:

http://cytoscape.org/cytoscape-automation/for-scripters/R/notebooks/Differentially-expressed-genes.nb.html

on lines 180/181 and 260/261, there's this code that includes two commands:

commandsRun('string retrieve enrichment allNetSpecies="Homo sapiens"')
commandsRun('string show enrichment')

When I run this as one chunk, it only does the first command. To get the enrichment results table to show, I either have to run the whole thing again, or run each line separately.

**Comment by AlexanderPico** [comment]
'string show enrichment' is a toggle. This is a stringApp commands bug. I'll file stringApp bug.
