### ISSUE TITLE
GeneMania Attributes

### ISSUE THREAD

**Issue by valentinapapa** [cytoscape/RCy3#165]
Hello,
I'm trying to use genemania through R. 
The problem I encounter is in importing some types of networks.
I would need to create a network with the following characteristics:
organism = Homo Sapiens
networks = Pathway, Genetic Interactions, Physical Interactions, Predicted, **Consolidated-Pathways-2013**
combiningMethod = Go biological process-based
attrLimit = 100
geneLimit = 100
genes = KRAS

For this reason, the query I enter is:

genemania_command<- "genemania search organism=9606 networks=path,pi,gi,predict combiningMethod=BP attrLimit=100 geneLimit=100 genes= KRAS"
commandsRun(genemania_command)

How can I also provide the Consolidated-Pathways-2013 as input?
Furthermore, for another type of network, I would need to provide the **Drug-interactions-2020** attribute as input. How can I do?

**Comment by AlexanderPico** [comment]
Sorry for the delayed response. This is not an RCy3 issue, however. The [GeneMANIA app developers](https://apps.cytoscape.org/apps/genemania) are responsible for defining the supported commands and attributes for their app. RCy3 simply passes them along to CyREST.

If you have a query that works in CyREST or in the Command Line Tool in Cytoscape, **_but not in RCy3_**, then we'd have an RCy3 bug.
