### ISSUE TITLE
creation of networks using createNetworkFromIgraph()

### ISSUE THREAD

**Issue by peranti** [cytoscape/RCy3#166]
Hello,

Thanks a lot for this handy package.

I have a STRING network of 12,086 vertices and  249,980 edges as igraph object. Based on the previous experience with `RCy3::createNetworkFromIgraph()`, I tried to use the same approach. However, the network in Cytoscape is yet to be generated even after 12+ hours. 

Is it advisable to use  `createNetworkFromIgraph()` for this large size graph? What is the best approach to use to create networks of different node sizes (e.g: 500, 5000, 10000, 15000, ...)?

**Comment by AlexanderPico** [comment]
Sorry for the late response.  That's a big one for the automation package! You are blazing a new trail. I don't know of anyone else working with such networks using RCy3, so I don't have any particular advice to give.  You are figuring out the limits of size and time per your machine. That's the only way to do it.

The only tip I could give would be to set all the delays to zero as they may be introducing pauses that are not needed. Can only tell by trial and error.

```
    setCatchupFilterSecs(0)
    setModelPropagationSecs(0)
    setCatchupNetworkSecs(0)
```
