### ISSUE TITLE
In addAnnotationText (and others), name check seems misplaced

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/RCy3#171]
In addAnnotationText and other functions, there is a check to make sure the caller can't create two annotations of the same name. But it's pretty easy to get around the check, and Cytoscape seems to be fine with this. Try:

add_annotation_text(text='ann1')
add_annotation_text(text='ann2')

In this situation, I get two annotations, both with name "text", which Cytoscape assigned.
Should add_annotation_text (and other annotation functions) be checking for a duplicate name after all??

It seems like Cytoscape is OK with duplicate names, and users can easily create them via the Cytoscape UI.

**Comment by AlexanderPico** [comment]
Yeah, it's technically ok, but not a great idea. So, this encourages best practice without enforcing it.

**Comment by bdemchak** [comment]
I'm re-opening this pending the solution to CSD-678. It could well be that Cytoscape can't handle annotations with multiple names when the names are duplicated across multiple networks. 

But for that, I think you're still arguing for keeping this check in, and you don't care about the case where the user uses the GUI to create duplicate names.

True?

**Comment by AlexanderPico** [comment]
True. Mixed use (GUI + automation) is fraught with peril for many reasons. This is just one very very minor one :)
