### ISSUE TITLE
Conflicting Brightness/Contrast documentation

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/RCy3#172]
The documentation for addAnnotationImage indicates that brightness and contrast values have range 0..100, but the RCy3-utils.checkBrightnessContrast uses -100..100. Which is correct?

**Comment by AlexanderPico** [comment]
It's 0 to 100. I was just being lazy and reusing a check we already had in utils for other functions. It all works, but indeed gives the (wrong) impression that values between -100 and 0 will be different... and they are not in this case.

**Comment by bdemchak** [comment]
Not so sure about this. If I use the Cytoscape GUI to insert an annotation image, I see the sliders for contrast and brightness running -100..100. 

Would you take another look at this? If they really should be 0..100, I'll need to file a Cytoscape bug report.

Or am I not seeing this right?

**Comment by AlexanderPico** [comment]
I just added an image with -100 and 0 and they looked the same. That's all I know. Scooter might know how it actually works.

**Comment by AlexanderPico** [comment]
I was wrong. Reverting back to original code.
