### ISSUE TITLE
Conflicting Opacity documentation

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/RCy3#173]
The various flavors of opacity (opacity, borderOpacity) in addImageAnnotation and other functions indicate a range of 0..100. The RCy3-utils.checkOpacity function enforces 0..255. Which is correct?

**Comment by AlexanderPico** [comment]
It's 0..100. I was being lazy and reusing existing checks.

**Comment by bdemchak** [comment]
Thanks. py4cytoscape now matches this.
