### ISSUE TITLE
Conflicting Brightness/Contrast defaults in addImageAnnotation documentation

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/RCy3#174]
The documentation for brightness and contrast indicate a default value of 100, but the Cytoscape UI uses 0. Which should it be?

**Comment by AlexanderPico** [comment]
Good question for  @scootermorris. What do you think is best? Do they need to be the same? Which is "easier" to change for devs and for users?

**Comment by AlexanderPico** [comment]
Should be zero. Man pages updated.

**Comment by bdemchak** [comment]
I think Scooter indicated that -100..100 is the correct range. Agree??

**Comment by AlexanderPico** [comment]
Agreed. And here is a screenshot of man page from latest code:
![Screen Shot 2022-03-19 at 11 25 56 AM](https://user-images.githubusercontent.com/1418193/159133842-6e29adfa-93df-40cb-90ab-2a155c2a1366.png)
