### ISSUE TITLE
ungroupAnnotation cleanup

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/RCy3#176]
The groupAnnotation function allows the names parameter to be either a list or a comma-separated string. Should upgroupAnnotation (and deleteAnnotation) allow the same?

**Comment by AlexanderPico** [comment]
Sure, why not. Current code supports lists for all three.

**Comment by bdemchak** [comment]
py4cytoscape now allows lists in delete_annotation and ungroup_annotation
