### ISSUE TITLE
mergeNetworks: Error: $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by veroniquevoisin** [cytoscape/RCy3#179]
Hi,
I was using the mergeNetworks function and an error was thrown :Error: $ operator is invalid for atomic vectors
However the merged network is created with no apparent issue.
I'm just reporting it in case this feedback is helpful.

RCy3::mergeNetworks(c("mir20CBAML_1", "genemania"), "mir20CBAML", nodeKeys=c("name","query term"))
Error: $ operator is invalid for atomic vectors

**Comment by AlexanderPico** [comment]
Thanks for reporting this, @veroniquevoisin!

**Comment by yihangx** [comment]
@AlexanderPico As Barry mentioned, this is related to https://cytoscape.atlassian.net/browse/CSD-668.

**Comment by AlexanderPico** [comment]
@yihangx Are you saying this is a cyrest issue that will be fixed when cyrest is updated? Or it is an RCy3 issue that is related to the other issue, but requires a fix to RCy3 code as well?

**Comment by yihangx** [comment]
@AlexanderPico I coordinated with Mike, and he said this is a cyrest issue. It will be fixed when cyrest is updated.

**Comment by AlexanderPico** [comment]
Great! We'll leave this open until we can confirm, but in the meantime, there isn't anything we can do in RCy3 to fix this.

**Comment by melissaszy** [comment]
Hello. I am currently facing this issue:

> mergeNetworks(c("network1.sif", "network2.sif"), "merged_network")
Error in res.data$SUID : $ operator is invalid for atomic vectors

Am I right to say that the merged_network is accurate and can be used despite the error message? 


Cheers!

**Comment by yihangx** [comment]
@melissaszy If the merged network result is correct, then you do not need to worry.

**Comment by melissaszy** [comment]
@yihangx thank you for your help. the number of nodes and edges are correct, so I shall proceed and use the merged network. Thanks again!
