### ISSUE TITLE
Add importFileFromUrl as duplicate of sandboxUrlTo function

### ISSUE THREAD

**Issue by yihangx** [cytoscape/RCy3#182]
To sync with the latest py4cytoscape, this function should be revised. Rename it as importFileFromUrl and put it in Tools.R. Other sandbox related functions may also need change.

**Comment by bdemchak** [comment]
Good ... more precisely, the sandbox_from_url() function should remain untouched. It's valuable and proper in its current form. The change would be to create a *new* function import_file_from_url() in tools. It would call sandbox_from_url() with a null session name so as to cause the download to occur in the current sandbox, which (on the local workstation) would be the file system.

**Comment by AlexanderPico** [comment]
Agreed. Renaming or removing a function requires two major releases in Bioconductor with deprecation and defunct notices over a year. It is much simpler to just add new function, even if the new one just calls the current one.

**Comment by bdemchak** [comment]
Right ... and the new function would not accept the sandbox name ... sandboxes are irrelevant in this context. But it would call the sandboxURLTo function with a None sandbox name. So, the functions aren't identical ... each to its own context.

**Comment by yihangx** [comment]
Implemented importFileFromUrl in Tools.R.
