### ISSUE TITLE
network load file

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/RCy3#183]
**Reported by Barry: https://cytoscape.atlassian.net/browse/CYTOSCAPE-12772** 

I think the problem was with the original bug report. The failure actually occurs with network load file command instead of the network import file command:

network load file file="C:\\Users\CyDeveloper\Desktop\BIOGRID-ORGANISM-Saccharomyces_cerevisiae-3.2.105.mitab"

The command window reports:

-> org.cytoscape.view.model.internal.NullCyNetworkViewImpl@28731de0

CyREST/Swagger produces this:

{
"data": {},
"errors": [{"status": 500,"type": "urn:cytoscape:ci:cyrest-core:v1:handle-json-command:errors:3","message": "Task returned invalid json.","link": "file:/C:/Users/CyDeveloper/CytoscapeConfiguration/3/framework-cytoscape.log"
}]}

I’m able to reproduce in Python using this:

import py4cytoscape as p4c

p4c.import_network_from_file('C:/Users/CyDeveloper/Desktop/BIOGRID-ORGANISM-Saccharomyces_cerevisiae-3.2.105.mitab')

This resolves to a Python HTTP POST of:

'[http://127.0.0.1:1234/v1/commands/network/load file](http://127.0.0.1:1234/v1/commands/network/load%20file)'

{'json': {'file': 'C:\\Users\CyDeveloper\Desktop\BIOGRID-ORGANISM-Saccharomyces_cerevisiae-3.2.105.mitab'}, 'headers': {'Content-Type': 'application/json', 'Accept': 'application/json' }}

The HTTP return is 200, but the content is:

{"data": {},

"errors": [{"status":500,"type":"urn:cytoscape:ci:cyrest-core:v1:handle-json-command:errors:3","message":"Task returned invalid json.","link":"file:/C:/Users/CyDeveloper/CytoscapeConfiguration/3/framework-cytoscape.log"}]}

The “Task returned invalid json” is he problem.

**Comment by yihangx** [comment]
This is normal behavior of Cytoscape. Nothing to fix here.
