### ISSUE TITLE
enhancement: setNodeColorBypass: List of hex colors 

### ISSUE THREAD

**Issue by veroniquevoisin** [cytoscape/RCy3#188]
enhancement idea: setNodeColorBypass: List of hex colors 
it would be easier if we could use R color names ("red", "blue") in addition to hex numbers. It is possible with the setNodeCustomPieChart function.
Thanks!!

**Comment by AlexanderPico** [comment]
Plan: import `gplots`, then check colors against _`colors()`_ and call _`col2hex()`_. Modify _`.checkHexColor()`_ to perform this conversion prior to hex check and then change all instances to accept returned hex code: https://github.com/cytoscape/RCy3/search?q=.checkHexColor

**Comment by AlexanderPico** [comment]
Check for consistency:
- setEdgeColorBypass
- setNodePropertyBypass
- setEdgePropertyBypass
- setNodeCustomBarChart

**Comment by bdemchak** [comment]
Also add the following?

setNodeCustomBoxChart
setNodeCustomHeatMapChart
setNodeCustomLineChart
setNodeCustomPieChart
setNodeCustomRingChart
setNodeCustomLinearGradient
setNodeCustomRadialGradient

**Comment by yihangx** [comment]
Fixed.
