### ISSUE TITLE
suggestion: selectEdgesAdjacentToSelectedNodes ; add  nodes in function so we don't have to run selected nodes just before

### ISSUE THREAD

**Issue by veroniquevoisin** [cytoscape/RCy3#190]
just a suggestion in case it helps: selectEdgesAdjacentToSelectedNodes ; add  nodes in function so we don't have to run selected nodes just before)
##current
Selectednodes = selectNodes(
  nodes = unlist(drugnetwork1$V1),
  by.col = "name",
  preserve.current.selection = TRUE,
  network = "network1",
  base.url = "http://localhost:1234/v1"
)

selectEdgesAdjacentToSelectedNodes(
   network = "network1",
  base.url = "http://localhost:1234/v1"
  )

##suggestion
selectEdgesAdjacentToSelectedNodes(
  **nodes = unlist(drugnetwork1$V1)**,
   network = "network1",
  base.url = "http://localhost:1234/v1"
  )

**Comment by AlexanderPico** [comment]
Nice idea. If we add a new `nodes` param to that function, however, it would potentially break existing scripts (e.g., that pass in a `network` as first arg).  The process for deprecating and old function and replacing it takes two cylcles of Bioconductor releases (a year). So, an alternative solution might be to introduce a new function: `selectEdgesAdjacentToNodes` with the params you suggested. 

Would this work for you?

**Comment by yihangx** [comment]
The new function is implemented.

**Comment by veroniquevoisin** [comment]
yes, sure!
