### ISSUE TITLE
setNodeSizeMapping doesn't recognize base.url

### ISSUE THREAD

**Issue by risserlin** [cytoscape/RCy3#191]
setNodeSizeMapping doesn't work for different base.urls

Able to connect to cytoscape but unable to use function.  I think that all the visual style methods use the same general functions so this might apply for a whole chunk of methods.  

RCy3 version 2.17.1

![Screen Shot 2022-09-21 at 1 31 15 PM](https://user-images.githubusercontent.com/3842763/191572033-6fcd805a-8b4e-4895-8329-d640fa2c3745.png)

**Comment by AlexanderPico** [comment]
Great find! Found the culprit. Fixed and pushed to GitHub. Can install from there, manually define an updated version of `setStyleDependencies`, or wait for Nov release from Bioc. Thanks for reporting this before this upcoming release!

**Comment by AlexanderPico** [comment]
Dev note: already correct in py4cy. No need to copy this bug over.
https://github.com/cytoscape/py4cytoscape/blob/master/py4cytoscape/style_dependencies.py#L74

**Comment by risserlin** [comment]
Hi Alex, 
Thanks for the quick turn around.  I have been using the dev version to use the new changes but the one from yesterday is coming up as corrupt for some reason (not sure if it is from my side or not)
![Screen Shot 2022-09-22 at 10 09 48 AM](https://user-images.githubusercontent.com/3842763/191769850-73bb22ab-c9e7-4b84-8913-478b06a21edf.png)

If I roll back to the previous github fix it works though - 
 devtools::install_github("Cytoscape/RCy3",ref="7984f0b")

Thanks, 
Ruth

**Comment by AlexanderPico** [comment]
Works for me:
* uninstall RCy3 (I use the RStudio GUI, 'x' in Packages tab, not checkbox)
* install_github('cytoscape/RCy3', build_vignettes=FALSE)
* library(RCy3)

**Comment by AlexanderPico** [comment]
An rdb corruption might also require an R and RStudio reboot. Not sure.
