### ISSUE TITLE
mapping.type checks only work for single letter abbr

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/RCy3#192]
needed to cover full words (like continuous) and old words (like interpolate) in addition to abbr (like c)

**Comment by AlexanderPico** [comment]
dev note: py4cy requires use of c,d,p abbreviations, so this issue is not relevant

**Comment by bdemchak** [comment]
I don't think I understand why this wouldn't be relevant for py4cy ... if the caller supplies "interpolate", shouldn't it be used as a synonym for "continuous"? Same with "lookup"?

**Comment by AlexanderPico** [comment]
When I looked at py4cy code, it seemed like only c,d,p were allowed. 
https://github.com/cytoscape/py4cytoscape/blob/master/py4cytoscape/style_mappings.py#L2055

**Comment by bdemchak** [comment]
Not quite ... if caller provides 'c', it gets mapped to 'continuous' ... similar for 'd' and 'p'. 

But if it is something like "junktype", then "junktype" will be used. I think this might have been the way the original RCy3 code worked, but it looks like RCy3 is now throwing an error for this. (Could this be so?) So, Py4Cy should do the same thing.

... and "interpolate" and "lookup" should be mapped. 

Agree?

**Comment by AlexanderPico** [comment]
This issue wasn't about interpolate and lookup, really. Those were old rcy2 terms we grandfathered in, totally specific to old R users. Never supported by Cytoscape in general or python libs. So no.

This issue was that if someone used 'continuous' it would not work.  If your code works for both c and continuous then it's perfect, imo.

**Comment by bdemchak** [comment]
OK ... thanks.
