### ISSUE TITLE
Question: How do create column filters using multiple arguments?

### ISSUE THREAD

**Issue by veroniquevoisin** [cytoscape/RCy3#193]
I was able to create filter using 1 argument (1 column) but I need to create the filter using 3 columns (see below). I was not able to figure it out using the createColumnFilter function.

<img width="501" alt="Screen Shot 2022-10-07 at 12 09 30 PM" src="https://user-images.githubusercontent.com/7570379/194599894-98d68c9d-243d-4915-8d42-ffe6dba1ba0e.png">

What I tried (does not work):
createColumnFilter(
  filter.name = "toremove",
  column = c("C1", "C2", "C3"),
  criterion = c(1, 1, 1),
  predicate =  "IS_NOT" ,
  caseSensitive = FALSE,
  anyMatch = TRUE,
  type = "nodes",
  hide = FALSE,
  network = "C1_greatExportAll",
  base.url = "http://localhost:1234/v1"
)

**Comment by AlexanderPico** [comment]
Create each filter separately, then use `createCompositeFilter` to logically combine multiple filters. This abstraction is needed in order to support nested, combinations of filters.

**Comment by veroniquevoisin** [comment]
Perfect, it worked!
