### ISSUE TITLE
igraph issues

### ISSUE THREAD

**Issue by magnuspalmblad** [cytoscape/RCy3#20]
Dear Alexander et al.,

Perhaps this is something you are aware and working on, but there seems to be some issues with RCy3 and igraph. If I create a new CytoscapeWindow with an igraph graph object, I get the error message:

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘nodeDataDefaults’ for signature ‘"igraph", "missing"’

I have tried various examples, including some from igraphdata. I have the current versions of R (3.4.4), RCy3 (1.8.0) and igraph (1.2.1). However, R cannot find the functions cytoscapePing, cytoscapeVersionInfo, createNetworkFromIgraph or createIgraphFromNetwork.

The basic RCy3 communication with Cytoscape (3.6.1) for creating nodes, edges and applying layouts works fine, as long as I stay with the graphNEL model (which does not allow multiple edges between two nodes unless they are only two and in opposite directions). Minor issues would be that I have to displayGraph(cw) to see the new edges added with addCyEdge in Cytoscape, whereas this is not required for nodes.

Here is some example code I used for testing RCy3:

```
library(RCy3)
library(igraph)

# does not work:
deleteAllWindows(CytoscapeConnection())
g <- make_graph(c('Altstadt', 'Kneiphof',
                  'Kneiphof', 'Altstadt',
                  'Altstadt', 'Lomse',
                  'Vorstadt', 'Kneiphof',
                  'Kneiphof', 'Vorstadt',
                  'Vorstadt', 'Lomse',
                  'Kneiphof', 'Lomse'), directed = FALSE)

cw <- CytoscapeWindow('Koenigsberg', g)

# does work (at least in 'fresh' sessions, edges are seen as undirected in Cytoscape):

deleteAllWindows(CytoscapeConnection())
cw <- CytoscapeWindow('Koenigsberg')

# add nodes:
addCyNode(cw, 'Altstadt')
addCyNode(cw, 'Kneiphof')
addCyNode(cw, 'Vorstadt')
addCyNode(cw, 'Lomse')

# add edges (bridges):
addCyEdge(cw, 'Altstadt', 'Kneiphof', edgeType='bridge', directed=FALSE)
addCyEdge(cw, 'Kneiphof', 'Altstadt', edgeType='bridge', directed=FALSE)
addCyEdge(cw, 'Altstadt', 'Lomse', edgeType='bridge', directed=FALSE)
addCyEdge(cw, 'Vorstadt', 'Kneiphof', edgeType='bridge', directed=FALSE)
addCyEdge(cw, 'Kneiphof', 'Vorstadt', edgeType='bridge', directed=FALSE)
addCyEdge(cw, 'Vorstadt', 'Lomse', edgeType='bridge', directed=FALSE)
addCyEdge(cw, 'Kneiphof', 'Lomse', edgeType='bridge', directed=FALSE)

displayGraph(cw)
```

**Comment by magnuspalmblad** [comment]
I realized the Koenigsberg graph is also one of the datasets in the igraphdata package. But passing this graph through CytoscapeWindow() generates the same error message as the first test above.

**Comment by AlexanderPico** [comment]
Here is an updated script to perform the same steps using RCy3 v2.0

```
library(RCy3)
library(igraph)

# works now:
deleteAllNetworks()
g <- make_graph(c('Altstadt', 'Kneiphof',
                  'Kneiphof', 'Altstadt',
                  'Altstadt', 'Lomse',
                  'Vorstadt', 'Kneiphof',
                  'Kneiphof', 'Vorstadt',
                  'Vorstadt', 'Lomse',
                  'Kneiphof', 'Lomse'), directed = FALSE)

net.suid <- createNetworkFromIgraph(g, 'Koenigsberg')

# Also works:
deleteAllNetworks()
graph_data <- data.frame(source=c('Altstadt', 'Kneiphof','Altstadt','Vorstadt', 'Kneiphof','Vorstadt', 'Kneiphof'),
                         target=c('Kneiphof', 'Altstadt','Lomse','Kneiphof', 'Vorstadt','Lomse','Lomse'),
                         stringsAsFactors = FALSE)

net.suid <- createNetworkFromDataFrames(edges = graph_data, title = 'Koenigsberg')

# this should not be necessary, but doesn't hurt to make it explicit
setVisualStyle('default') 
```

**Comment by magnuspalmblad** [comment]
This works great - thanks! I think Cytoscape sees the edges as directed (I get the message that "The network contains only directed edges and they are not paired."), even when using make_undirected_graph or specifying directed = FALSE as in the above example. Normally this is not a problem in Cytoscape, as edge directionality can be ignored, but it should probably be corrected.

**Comment by magnuspalmblad** [comment]
I understand undirected graphs has a long (and perhaps painful) history in Cytoscape, but for someone 
coming from igraph, it may be confusing when
```
createNetworkFromIgraph(g)
g<-createIgraphFromNetwork()
``` 
turns an undirected graph into a directed one.

**Comment by AlexanderPico** [comment]
Right. I don't think Cytoscape actually has proper support for undirected networks. It just let you ignore it (visually and analytically) if you choose to. So, I don't see a "fix" for this round trip issue.

However, I am more than happy to document it. I'll add it to the method docs and the vignette about RCy3 and iGraph. Thanks!

**Comment by AlexanderPico** [comment]
Done: https://github.com/cytoscape/RCy3/commit/b7f258a5957bd095d6594432f6cdb3d6e2a1b315
