### ISSUE TITLE
Missing edge attributes in networks with multiple edges

### ISSUE THREAD

**Issue by jd690764** [cytoscape/RCy3#203]
I have a similar issue as in #41. I repeated the first example and some of the attributes are not shown in the edge table (see attached screenshot). 

RCy3 - 2.18.0
iGraph - 1.4.2
Cytoscape - 3.9.1
R - 4.2.2

<img width="1317" alt="Screenshot 2023-05-09 at 6 28 11 PM" src="https://github.com/cytoscape/RCy3/assets/10483811/7827de67-0d81-42ad-9023-0cc61193d271">

Any help would be much appreciated.
Thanks,
Janos

**Comment by AlexanderPico** [comment]
Indeed. We fixed this in March of 2021 (#115), but then broke it again 7 months later trying to fix #139. We need to try again and thoroughly test all the various edge cases.

@jd690764 As a immediate fix, you can run this code to replace the function with the older version that works for your use case:
```
.edgeNameToEdgeSUID<-function(edge.names, network=NULL, base.url=.defaultBaseUrl) {
        dict <- getTableColumns('edge',c('SUID','name'),'default',network, base.url)
        test <- vapply(edge.names, function(x){x %in% dict[,'SUID']}, logical(1))
        if(all(test))  #provided SUIDs already!
            return(edge.names)
        sorted.dict <- NULL
        if(length(edge.names) == length(unique(edge.names))){ #unique edge names
            sorted.dict <- dict[match(edge.names, dict$name), ] 
        } else { #multigraph: multiple edges with the same name
            message("Finding unique SUIDs for edges with the same name...\n")
            match_list <- list()
            for(i in seq_along(edge.names)){ #perform match with removal
                name_match <- dict[match(edge.names[[i]], dict$name),]
                match_list[[i]] <- name_match
                dict <- subset(dict, SUID != name_match$SUID)
            }
            sorted.dict <- do.call(rbind, match_list)
        }
        edge.SUIDs <- sorted.dict$SUID
        return(edge.SUIDs)
}
```

**Comment by yihangx** [comment]
@jd690764 Hi, this bug is fixed.  To use the latest RCy3, you can either clone the RCy3 repo and build devel branch locally by running devtools::document(), or you can download development version 2.21.1 from https://bioconductor.org/packages/devel/bioc/html/RCy3.html, it take few days to see update in the bioconductor website.

**Comment by AlexanderPico** [comment]
@jd690764 No need to clone and build. You can install R packages directly from GitHub with these steps from our README:

```
install.packages("devtools")
library(devtools)
install_github('cytoscape/RCy3', build_vignettes=FALSE)
library(RCy3)
```

**Comment by jd690764** [comment]
Thank you!
Janos
