### ISSUE TITLE
The running version of CyREST has changed. CyREST requires a restart of Cytoscape to function correctly

### ISSUE THREAD

**Issue by Peipenggang** [cytoscape/RCy3#205]
Hello, 
I can't use cytoscape plugin Giant and I have installed cytoscape 3.8.0 and the application itself is working. Can you help me?
Thanks!
Note: I am using Mac.

The warning information: The running version of CyREST has changed. cyREST requires a restart of Cytoscape to function correctly

**Comment by Peipenggang** [comment]
<img width="1225" alt="截屏2023-06-05 22 19 43" src="https://github.com/cytoscape/RCy3/assets/105035255/10f5d13b-0d59-471e-a749-4ddeeecacc35">
When I press 'Compute', only the nodes in the picture turn red and there will be no more response.

**Comment by bdemchak** [comment]
Have you considered trying all of this with current Cytoscape, which is
3.10? ... 3.8 is pretty old, and would be hard to give good answers for.

**Comment by Peipenggang** [comment]
Well, I have tried to use Cytoscape 3.10, surprisingly, I even can't install the plugin GIANT.

**Comment by Peipenggang** [comment]
<img width="1225" alt="截屏2023-06-06 08 45 41" src="https://github.com/cytoscape/RCy3/assets/105035255/38bc9b93-d110-4ec1-b925-036c103e6ae0">
The same question  when I used Cytoscape 3.10, When I press 'Compute', only the nodes in the picture turn red and there will be no more responses and  the cytoscape  was in a crash state and I had to force quit.

**Comment by yihangx** [comment]
@Peipenggang This is not a RCy3 issue, but I would like to help if you can provide me your session file and node attributes.

**Comment by Peipenggang** [comment]
I am sorry and I cannnot provide session file and node attributes because cytoscape was in a crash state, and I tried to use troubleshooting code to check it,
Cytoscape System Requirements Checker for Mac,  even though I have installed openJDK successful , it suggested No JDK found.
##############
Target Cytoscape version: 3.9.1
Your shell is zsh
Compatible OS version found: 13
 - Pass: OS Version = 13.2.1
- Fail: No JDK found.  Please download and install a compatible JDK, such as AdoptOpenJDK:
https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=hotspot
 - Pass: Current Java Version = 11.0.13
 - Pass: JAVA_HOME found: /Users/penggangpei/opt/miniconda3
Checking connection to Cytoscape App Store...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 50593    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Done!  You are ready to run Cytoscape 3.9.1

**Comment by yihangx** [comment]
@Peipenggang 

The warning information just remind you the cyREST changed. You can just restart Cytoscape and ignore it.

Also, No JDK found will not cause this bug. From my perspective, it is an issue about GIANT app itself.

Since this is not a RCy3 issues, please report your bug here (https://cytoscape.org/bug-report.html). Then I can discuss it  with the whole Cytoscape team.

Meanwhile, you can contact the author of GIANT app, you can find his email under the app store page. Since this app was published ~10 years ago, I doubt they are still maintain the app, it still worth a try.
