### ISSUE TITLE
openSession() fails with Cytoscape_v3.10.1 on debian v12

### ISSUE THREAD

**Issue by rafalcode** [cytoscape/RCy3#211]
default linux installation of Cytoscape has sampleData folder  in its root directory
openSession() seems to look inside the "framework" subfolder for it causing an error
Quick solution is to symbolically link "sampleData" in "framework" aka.
```/opt/Cytoscape_v3.10.1/framework$ ln -s ../sampleData```

**Comment by AlexanderPico** [comment]
Good catch. That is indeed the solution we recommend. If you have a patch for detecting linux and finding the "right" place consistently across distos, we would welcome it!
