### ISSUE TITLE
No return value comes from the cytoscapePing function with the changed base.url parameter.

### ISSUE THREAD

**Issue by kozo2** [cytoscape/RCy3#212]
# The screen shot
![image](https://github.com/cytoscape/RCy3/assets/12192/f254e481-18f6-4656-9115-82d3035076e1)

# How to reproduce this issue
1. Install Docker and Docker Compose
2. run `mkdir trycydocker` command in your terminal.
3. run `cd trycydocker` command in your terminal.
4. copy [.env](https://github.com/cytoscape/docker-cytoscape-desktop/blob/master/.env) and [compose.yml](https://github.com/cytoscape/docker-cytoscape-desktop/blob/master/compose.yml) to the `trycydocker` directory
5. run `docker-compose up -d` command in the `trycydocker` directory.
6. open `http://localhost:8888/lab` and `http://localhost:6080/vnc_auto.html` in your web browser.
7. In `http://localhost:8888/lab`, create a Notebook [for R] and run
    ```
    if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

    BiocManager::install("RCy3")
    library(RCy3)
    cytoscapePing(base.url = 'http://cytoscape-desktop:1234/v1')
    ```

**Comment by yihangx** [comment]
@kozo2 Can you install devel branch and try it again?

**Comment by kozo2** [comment]
@yihangx I installed the devel branch and tried it, but unfortunately, the issue persists.
Do you have any other suggestions?

![image](https://github.com/cytoscape/RCy3/assets/12192/8c9195a9-284c-4350-a75e-5168f75fecc4)

**Comment by yihangx** [comment]
@kozo2 Could you try it again? It worked in my docker image.

**Comment by kozo2** [comment]
@yihangx I tried it again (for RCy3_2.21.3.tar.gz).
It worked also in my docker image.
![image](https://github.com/cytoscape/RCy3/assets/12192/fa6e5a53-2904-441b-b751-edb4ec2e25a6)
