### ISSUE TITLE
Missing node label position and label position functions

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/RCy3#214]
Looking over style functions, I see some missing functions:

* setNodeLabelPosition() missing ... getNodeLabelPosition() does exist
* getNodeLabelPositionBypass() missing ... setNodeLabelPositionBypass() does exist
* getNodePositionBypass() missing ... setNodePositionBypass() does exist

Is there a reason for this asymmetry? 

BTW, py4cytoscape is missing the following, and I'll be adding them to match the RCy3 functions:

* set_node_label_position_default
* get_node_label_position_default

* get_node_label_position

* set_node_label_position_bypass

* set_node_position_bypass

**Comment by bdemchak** [comment]
Don't implement getNodeLabelPositionBypass() or getNodePositionBypass() because there are no get*Bypass functions for any other properties.

**Do implement** getNodeLabelPosition() because it makes testing setNodeLabelPosition() easier and is useful anyway

I added the following in py4cytoscape:

* set_node_position_bypass

* set_node_label_position_bypass

* get_node_label_position_default

* set_node_label_position_default

* get_node_label_position

**Comment by yihangx** [comment]
@bdemchak  getNodeLabelPosition() is already here: https://github.com/cytoscape/RCy3/blob/ae1e499b6eed2d21a1e205966f606e17238d6d00/R/StyleValues.R#L285

Do you mean some other functions?
