### ISSUE TITLE
Error in Pathway Analysis vignette 

### ISSUE THREAD

**Issue by mauritsunkel** [cytoscape/RCy3#217]
Hi, following this vignette (https://bioconductor.org/packages/release/bioc/vignettes/rWikiPathways/inst/doc/Pathway-Analysis.html) everything runs fine until: 
```
em_command = paste('enrichmentmap build analysisType="generic" ', 
                   'pvalue=',"0.05", 'qvalue=',"0.05",
                   'similaritycutoff=',"0.25",
                   'coeffecients=',"JACCARD",
                   'enrichmentsDataset1=',egobp.results.filename ,
                   sep=" ")

  #enrichment map command will return the suid of newly created network.
  em_network_suid <- commandsRun(em_command)
```
Failed to execute: http://127.0.0.1:1234/v1/commands/enrichmentmap/build?analysisType=generic&pvalue=%200.05&qvalue=%200.05&similaritycutoff=%200.25&coeffecients=%20JACCARD&enrichmentsDataset1=%20C:/Users/mauri/Documents/bulkmRNAseq_DEA/PEA_TB/clusterprofiler_cluster_enr_results.txt

Error in fromJSON(rawToChar(res$content))$errors : 
  $ operator is invalid for atomic vectors

What could I try?

**Comment by khanspers** [comment]
I see the same error. However, running the command (em_command) directly in the Command Line in Cytoscape works, so it seems this is RCy3 specific. 

Also, the code that creates the command has a typo, unrelated to the error above (placement of single quote for analysisType):

```
em_command = paste('enrichmentmap build analysisType=',"generic", 
                    'pvalue=',"0.05", 'qvalue=',"0.05",
                    'similaritycutoff=',"0.25",
                    'coeffecients=',"JACCARD",
                    'enrichmentsDataset1=',egobp.results.filename ,
                    sep=" ")
```

**Comment by AlexanderPico** [comment]
Hmm... CyREST is returning a 500 status for this command, which is triggering the error clause in the code, which is returning this (ugly) error message.

And if I tease out the error message manually, I get:

> "None of the gene sets have passed the filter. Try relaxing the gene set filter parameters."

Which is the same error I get when I run the analysis via CyREST Swagger: http://127.0.0.1:1234/v1/swaggerUI/swagger-ui/index.html?url=http://127.0.0.1:1234/v1/commands/swagger.json#!/enrichmentmap/enrichmentmap_build

Even though there are gene sets that pass the filter and the same command generates results via CLI.

So, it's not an rWikiPathways nor RCy3 error. It appears to be an issue with enrichmentmap app in how it's handling queries coming from CyREST vs. CLI, even with identical parameters.

Adding @risserlin to ticket to see if she has any additional insights.

**Comment by AlexanderPico** [comment]
@khanspers when you get a chance, can you update the vignette to fix the non-critical typo you found as well as this one:

coeffecients ==> coefficients (the typo version still works, but is deprecated)

**Comment by bdemchak** [comment]
@Alex Pico ***@***.***> Does py4cytoscape return the same
ugly error??

**Comment by AlexanderPico** [comment]
Open issue in enrichmentmap repo: https://github.com/BaderLab/EnrichmentMapApp/issues/532

**Comment by AlexanderPico** [comment]
> @alex Pico ***@***.***> Does py4cytoscape return the same ugly error??

Nope. Unique R problem. Python doesn't use those `$` shortcuts. https://github.com/cytoscape/py4cytoscape/blob/master/py4cytoscape/commands.py#L674

**Comment by AlexanderPico** [comment]
@yihangx can you look into better syntax here for parsing the error without creating a new error :)

https://github.com/cytoscape/RCy3/blob/devel/R/Commands.R#L828C76-L828C76

**Comment by yihangx** [comment]
Sure!

**Comment by risserlin** [comment]
This looks like an issue with the current version of EM that is in the app store(3.3.6).  I can not recreate this issue with the development version of EM that I have installed but I was able to recreate it with EM 3.3.6.  @mikekucera what is the time line for the release of the next version of EM?  Can we maybe release an update of EM with the fix for the above issue?

**Comment by AlexanderPico** [comment]
Got CyREST to work by using correct Datasets arg, so that is not the source of the issue.  Back to looking RCy3...

Currently stumped.

**Comment by mauritsunkel** [comment]
Hi, checking in if this issue is still on the radar.

Maybe in the meantime would you be able to recommend me a workaround?

**Comment by AlexanderPico** [comment]
Sure. The workaround is to use CyREST directly, using the `enrichmentsDataset1` parameter name. See https://github.com/BaderLab/EnrichmentMapApp/issues/532.

**Comment by yihangx** [comment]
Kristina and I cannot reproduce this one.
