### ISSUE TITLE
Cannot Create network from graphNel/igraph object, generated from kgml

### ISSUE THREAD

**Issue by Naadir-Ganief** [cytoscape/RCy3#220]
Hi,

below is the code i was trying, I tried both the graphNel and igraph objects, both return the same error : "Error in FUN(X[[i]], ...) : environments cannot be coerced to other types"

parsed.kgml <- KEGGlincs::get_KGML(pathwayid = pathIds[[1]], get_if_no_edges = F)
    
    graphNel <- KEGGgraph::parseKGML2Graph(file = kgml, genesOnly = T, expandGenes = F)
    
    
    igraph <- graph_from_graphnel(graphNEL = graphNel)
    
    plot(igraph)
      
    
    RCy3::createNetworkFromIgraph(
      igraph,
      title = "From graph",
      collection = "My GraphNEL Network Collection"
      
    )

Thanks

**Comment by AlexanderPico** [comment]
Duplicate? https://support.bioconductor.org/p/9159835/

I'm not surprised that this fails. Not all GraphNELs nor igraphs are the same, so these chains of conversions are fraught with peril. Assuming the goal is creating the network in Cytoscape (given the final lines you shared), here are some shorter routes:

* RCy3::createNetworkFromDataFrames(). If you can extract a simple node and edge dataframes from the parsed KGML, then you have more transparent control over the conversion and completely skip the poorly specified/implemented GraphNEL and igraph intermediates. [50/50 odds of working]
* RCy3::commandsRun('wikipathways import-as-pathway id="WP4020'). Skip KEGG altogether :) If you have the WikiPathways app installed in Cytoscape, then this one liner will perform the import. [100% odds of working]
