### ISSUE TITLE
WikiPathway arrows (Edges?) aren't aligned properly

### ISSUE THREAD

**Issue by zcsharp101** [cytoscape/RCy3#222]
Hi there,

The issue I am having is that when pathways with arrows are viewed on Cyctoscape, via the RCy3 package, they don't seem to be aligned in the same manor as they are on the website viewer. I have noticed this on many different pathways I have viewed. 

As an example I will post images from Cell Cycle (WP179) below and will attach the script I have used to generate the images with supporting data. The script needed to be changed to a .txt file to be uploaded but changing it back to a .R file will allow it to work fine.

[wikiPathways.GSEA+Pathway.Viewer_V2.-.copy_AP.txt](https://github.com/cytoscape/RCy3/files/15161617/wikiPathways.GSEA%2BPathway.Viewer_V2.-.copy_AP.txt)
[Treatment_vs_Ctrl.gene_summary - Copy.csv](https://github.com/cytoscape/RCy3/files/15161619/Treatment_vs_Ctrl.gene_summary.-.Copy.csv)

Thank you for the help.

**Comment by zcsharp101** [comment]
As viewed on the WikiPathways website:
![Website_view](https://github.com/cytoscape/RCy3/assets/167998688/ba054183-a385-4524-b922-af7cca4de0bd)

As viewed in Cytoscape via the RCy3 package website:
![Cytoscape_view](https://github.com/cytoscape/RCy3/assets/167998688/2454a48b-85eb-460c-bdcb-8f03ceb6b203)

**Comment by AlexanderPico** [comment]
Ah, yes. This has been a long-standing frustration that is not trivial to fix.  PathVisio (the app used to make WikiPathways diagrams) has anchor points around the borders of nodes that arrows can connect to. This is how you can have multiple connections along the top edge of a node that are separated by a bit of space. Cytoscape, on the other hand, can only connect to the center of a node. So, this is why the views are different. We can't easily recreate the separated anchor points in Cytoscape.

When I publish pathways figures from Cytoscape, as a final step after all the data overlays are complete, I will take time to clean up the arrows by moving their paths to help clarify things. It won't look exactly like it does in WikiPathways, but it can still be made clear.
