### ISSUE TITLE
Error when using setNodeColorMapping with igraph-generated graph

### ISSUE THREAD

**Issue by oneilsh** [cytoscape/RCy3#225]
Hello! I'm getting the dreaded "object 'res' not found" error when trying to set node colors via a property. Here's a minimal example:

```
library(igraph)
library(RCy3)

gt <- igraph::random.graph.game(10, 0.5)
gt <- igraph::set_vertex_attr(gt, "label", value = rep(c("A", "B"), each = 5))

cytoscapePing()
createNetworkFromIgraph(gt, "randgraph")
setNodeColorMapping('label')
```

And the produced output:

```
style.name not specified, so updating "default" style.
Error: Not Found
Error in cyrestPOST(paste("styles", style.name, "mappings", sep = "/"),  : 
  object 'res' not found
```

I've done a little bit of debugging, and I believe the error is appearing internal to the `cyrestPOST` function, specifically this `tryCatch` block:

```
		tryCatch(res <- POST(url = URLencode(q.url), body = q.body, 
			encode = "json", content_type_json()), error = function(c) .cyError(c, 
			res), warnings = function(c) .cyWarnings(c, res), 
			finally = .cyFinally(res))
```

My understanding is that if the `POST()` call does throw an error that gets caught, the `res` result will not be created, so can't be referenced in the `error`, `warnings`, and `finally` functions.

Anyway, that's the proximal error. Digging deeper while debugging I might have an issue with the install of `libcurl` on my mac (OSX 14.3), running just the `POST(url = URLencode(q.url), body = q.body, encode = "json", content_type_json())` at that point in the code gives me `Error in curl::curl_fetch_memory(url, handle = handle) : Unrecognized content encoding type. libcurl understands deflate, gzip content encodings.`. I haven't figured out how to solve that, but an improved `tryCatch` would help surface those kinds of errors more quickly :) (And any suggestions for fixing my libcurl would be welcome too!)

**Comment by AlexanderPico** [comment]
Thanks for the detailed report!  Indeed, this type of error is a "red herring" of sorts. The real issue is that the variable type in 'label' can't work with continuous mappings (not a continuous variable), which is the default for setNodeColorMapping(), so you need to provide the values and colors and override for discrete mapping, like these examples...

```
setNodeColorMapping('label',c('A','B'), colors=paletteColorBrewerSet3, mapping.type = 'd')
setNodeColorMapping('label',c('A','B'), colors=c("red","blue"), mapping.type = 'd')
setNodeColorMapping('label',c('A','B'), colors=c("#DD33AA","#33DDAA"), mapping.type = 'd')

```
