### ISSUE TITLE
Argument type unclear for setNodeColorMapping

### ISSUE THREAD

**Issue by dotasek** [cytoscape/RCy3#24]
The setNodeColorMapping function (https://github.com/cytoscape/RCy3/blob/b00d54118bd8ee2bbcdd396e93b9299548dc1195/R/StyleMappings.R#L275) doesn't appear to adequately document the input parameter ```table.column.values```. The correct input format appears to be:
```
setNodeColorMapping('verbal',table.column.values=c('0','1'),colors=c('#000000','#FFFFFF'),mapping.type='d') 
```

The documentation doesn't appear to specify this, and this may be repeated in the code for other instances of discrete mappings. Without the specification, some user have experienced difficulties: https://groups.google.com/d/topic/cytoscape-helpdesk/YsGGPyikZ-4/discussion

**Comment by AlexanderPico** [comment]
Fixed with https://github.com/cytoscape/RCy3/commit/f6c3082a7fe71703d453a1d1a5971a2f61ef1b71
