### ISSUE TITLE
calls missing base.url and crash when base.url <> default

### ISSUE THREAD

**Issue by vttrifonov** [cytoscape/RCy3#26]
There are many function call which take a base.url argument, provided to the calling function, but not passed on. For example look at the calls to getNetworkSuid in Tables.R. As a result if I try to call functions with base.url <> default (localhost:1234) RCy3 crashes. I have been fixing them in my clone (which fixes the crash) and I can send a patch when I am done, but I am doing it only when needed (i.e. a crash due to base.url) and not comprehensively.  This might need to be done right and the base.url feature tested more carefully.

**Comment by AlexanderPico** [comment]
Good catch! I think you're the first person to actually use this feature :)  Your feedback is much appreciated. 

I've got through all the code and update numerous cases for getNetworkSuid and a few other functions where this parameter was missing. I don't yet have testing setup for all these functions and for alt base.url. But the dev version of this package should be a much better starting point.

Feel free to install the direct form github to get these latest changes before they are pushed and officially released at Bioconductor: `install_github('cytoscape/RCy3')`
