### ISSUE TITLE
Setting base.url for exportNetworkToNDEx

### ISSUE THREAD

**Issue by ariutta** [cytoscape/RCy3#44]
This may be related to #26. Using version 2.1.13, I tried sending the pathway to the test NDEx server like this:

```
exportNetworkToNDEx(NDEX_USER, NDEX_PWD, isPublic=TRUE, base.url='http://test.ndexbio.org/v2')
```

But I got this error:
>RCy3::commandsPOST, HTTP Error Code: 500
 url=http://test.ndexbio.org/v2/commands/network/get%20attribute
 body={
 "network": "current",
"namespace": "default",
"columnList": "SUID" 
}
Error: $ operator is invalid for atomic vectors
Execution halted

If I use `exportNetworkToNDEx(NDEX_USER, NDEX_PWD, isPublic=TRUE, base.url='http://test.ndexbio.org')`

I get:
>RCy3::commandsPOST, HTTP Error Code: 404
 url=http://test.ndexbio.org/commands/network/get%20attribute
 body={
 "network": "current",
"namespace": "default",
"columnList": "SUID" 
}
Error in file(con, "r") : cannot open the connection
Calls: exportNetworkToNDEx -> getNetworkSuid -> commandsPOST
Execution halted

**Comment by AlexanderPico** [comment]
I suspect this is by design.  My mistake for thinking we should automate to the dev/test server. Let's just focus on automation for the production server case.
