### ISSUE TITLE
openSession should consider current wd 

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/RCy3#50]
cases:
- NULL -> sample session
- URL -> special case
- fullpath -> use as-is
- otherwise -> prefix with current working dir

**Comment by ariutta** [comment]
For the sample case, how is the relative path ([see this line](https://github.com/cytoscape/RCy3/blob/e205b1ad94f592cf4d889f842ea1da24ed73807e/R/Session.R#L51)) determined? It's not relative to the cwd.

**Comment by ariutta** [comment]
Strange, I tried it again and `test.filters` gave me this:

>------- test.filters
No nodes selected.
Error in checkEqualsNumeric(length(sel$nodes), 17) : 
  Mean relative difference: 0.2142857
Calls: run.tests -> test.filters -> checkEqualsNumeric
Execution halted
