### ISSUE TITLE
test for filters

### ISSUE THREAD

**Issue by ariutta** [cytoscape/RCy3#51]
Is the following expected when running the tests for filters?

> ------- test.filters
No nodes selected.
No nodes selected.

**Comment by ariutta** [comment]
That was what I got when I ran it for version 2.3.10.

**Comment by ariutta** [comment]
Strange, I tried it again and `test.filters` gave me this:

>------- test.filters
No nodes selected.
Error in checkEqualsNumeric(length(sel$nodes), 17) : 
  Mean relative difference: 0.2142857
Calls: run.tests -> test.filters -> checkEqualsNumeric
Execution halted

**Comment by AlexanderPico** [comment]
Yes, expected result.
