### ISSUE TITLE
Can't get node table for for WP186

### ISSUE THREAD

**Issue by ariutta** [cytoscape/RCy3#52]
Can't get node table for WP186:

```R
wikipathwaysID <- 'WP186'
net.suid <- commandsGET(paste0('wikipathways import-as-pathway id="', wikipathwaysID, '"'))
# FROM WIKIPATHWAYS APP
tableColumns <- getTableColumns()
```

yields this error:
> Error in x[[jj]][iseq] <- vjj: replacement has length zero

**Comment by ariutta** [comment]
Same error for WP2289 and WP4297.

**Comment by AlexanderPico** [comment]
Hmm... I could not reproduce this error. The tables for these pathways are returned without error. Are you using the release version of the WP app, version 3.3.7?  Maybe it's an issue with a beta-dev version of the app?

**Comment by AlexanderPico** [comment]
I just tested WP app 3.3.76, for example, and those pathways don't seem to load at all!  Suspect that beta-dev version of the app is buggy.
