### ISSUE TITLE
Exporting with non-ASCII filepaths

### ISSUE THREAD

**Issue by ariutta** [cytoscape/RCy3#54]
Export to CX via RCy3. Try opening that same file with the same filepath using [rjson](https://cran.r-project.org/web/packages/rjson/index.html)'s
`fromJSON`. You'll get an error for non-ASCII filepaths, e.g., any incl/ characters like Greek alpha: α such as for WikiPathways WP4566.

```R
filename <- "WP4566__Translational_regulation_by_PDGFRα__Homo_sapiens"
filepath_san_ext <- file.path(filename)
filepathCx <- paste0(filepath_san_ext, '.cx')
cx <- fromJSON(file=filepathCx)
```

Here's an example of where this is an issue:
https://github.com/wikipathways/wikipathways2ndex/blob/8b9c7282783a90a286d6c20d4c1cecedee72023e/wikipathways2cx.R#L49

How would we like to handle this behavior?

**Comment by AlexanderPico** [comment]
Fixed title. It was wrong anyways. Pathway titles shouldn't have non-ASCII characters.  

For your script, you can assume this or simply strip/replace them when constructing the filenames.
