### ISSUE TITLE
RCy3 Documentation Error

### ISSUE THREAD

**Issue by m-grimes** [cytoscape/RCy3#75]
Error in fetch(key) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RCy3/help/RCy3.rdb' is corrupt
Error in fetch(key) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RCy3/help/RCy3.rdb' is corrupt

Version RCy3_2.4.5     
 (recently updated)

**Comment by AlexanderPico** [comment]
HI Mark. I have no idea what this is...  How do you trigger this error? Any suggestions for a fix?

**Comment by m-grimes** [comment]
Alex,

I just upgraded to the new version this week, and was searching for syntax and this error came up. I haven’t tried rebooting or anything because I’m in the middle of something complicated. Perhaps there is a way to reload the new RCy3 and see if it goes away?

Mark

Mark Grimes
Division of Biological Sciences
University of Montana

On 3 Oct 2019, at 12:55, Alexander Pico wrote:

HI Mark. I have no idea what this is... How do you trigger this error? Any suggestions for a fix?
