### ISSUE TITLE
Why does getTableColumns('node') return single column?

### ISSUE THREAD

**Issue by kozo2** [cytoscape/RCy3#77]
`getTableColumns('node')` returns single column when the table has missing values.
But `getTableColumns('edge')` does not return single column even when the table has missing values.

What is the reason for this difference?

## How to reproduce this

```
library(RCy3)
installApp('KEGGscape')
library(httr)
GET("http://localhost:1234/keggscape/v1/mmu04150")
getTableColumns('edge')
getTableColumns('node')
```

**Comment by AlexanderPico** [comment]
That was to cover problems with NA handling in CyREST. But it looks like those are fixed now. So, I've removed that filter. All columns and rows are now returned for both nodes and edges. Install from github.

**Comment by kozo2** [comment]
Sorry for my late reply.
`getTableColumns('node')` works well now (version2.6.0).
Thank you.
