### ISSUE TITLE
SUID is returned from Networks.R/getNetworkName() 

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/RCy3#89]
In Networks.R/getNetworkName(), if the SUID is a network name and is found in the list of network names, the network's SUID is returned. Should it be the network name instead?

**Comment by AlexanderPico** [comment]
If you mean this line:
https://github.com/cytoscape/RCy3/blob/master/R/Networks.R#L117

It is returning the variable `suid` which in this case is the name of the network :)

**Comment by bdemchak** [comment]
Not an issue ... the name *is* returned. The confusion was with the variable name, not the value returned.
