### ISSUE TITLE
How to extract x and y values of all the nodes in a network

### ISSUE THREAD

**Issue by crotoc** [cytoscape/RCy3#91]
Hi there,
Thanks for your great package so that I can get my work done. I have a question whether there is a way to get the x and y values of all the nodes in a network. I am plotting a network and using yFile layout. Because yFile layout can not be accessed by RCy3, I have to apply the layout mannually. Then I need to extract the x and y values of this network to draw some more flexible network in R. Can you point me to the right direction. Thanks!

**Comment by m-grimes** [comment]
There used to be a function in the old RCy called getNodePosition() but 
I think that is depreciated? That was useful for copying layouts using 
the converse setNodePosition().

Mark

Mark Grimes
Division of Biological Sciences
University of Montana

**Comment by AlexanderPico** [comment]
We've  got `getNodePosition` and `layoutCopycat` for those use cases. Let me know if they don't do what you need.

**Comment by crotoc** [comment]
I can't find getNodePosition() and setNodePosition() as well. Can you guys give me more hints to how to use layoutCopycat? Thanks!

By the way, RCy3 is not possible to invoke yFiles, right? Is it a way to work around so that I can automate my whole workflow. Thanks!

**Comment by crotoc** [comment]
Bing! The getNodePosition does exactly what I want. Thanks very much!
 
By the way, RCy3 is not possible to invoke yFiles, right? Is it a way to work around so that I can automate my whole workflow. Thanks!

**Comment by AlexanderPico** [comment]
Correct. yFiles is provided by a for-profit company. They generously allow us to include it in Cytoscape for free, but they very clearly will not allow for automation. The automation of their layouts is what they charge money for. No way around this except by purchasing their projects...

**Comment by crotoc** [comment]
Okay! I tred to use their libs but I am really bad at Java, so doesn't know how to get layout info from their lib.... Can I know whether there is a layout good for GO (hierarchy layout/directed acyclic graph )? The current default ones are really not good for this purpose. Thanks!
