### ISSUE TITLE
Error in the last step of the createNetworkFromDataFrames - layoutNetwork?

### ISSUE THREAD

**Issue by GoBinn** [cytoscape/RCy3#94]
When I specify the base.url,layoutNetwork as the last step of the createNetworkFromDataFrames  doesn't use the base.url.
![微信截图_20200612181937](https://user-images.githubusercontent.com/31228062/84492765-44c71580-acd9-11ea-842a-a8624078882e.png)

**Comment by AlexanderPico** [comment]
Good catch! Thanks for the error report and solution. I've commited the fix. It will be availabe on bioconductor in a couple days. It's available now via github:

```
install.packages("devtools")
library(devtools)
install_github('cytoscape/RCy3', build_vignettes=TRUE)
```
