### ISSUE TITLE
setNodeColorMapping error

### ISSUE THREAD

**Issue by richabatra** [cytoscape/RCy3#97]
Hi, 

I am getting this error. Is it a known one? 

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Unrecognized content encoding type. libcurl understands deflate, gzip content encodings.

Cytoscape version 3.7.2, R version 3.6.2, RCy3 2.6.3, Mac OS.

Happy to provide more details and toy example if needed. 

Thanks

**Comment by AlexanderPico** [comment]
Resolved by OP. Installation issues, I presume.  Would recommend updating Cytoscape, R and RCy3 versions.

**Comment by richabatra** [comment]
No, it was base.url setting. I have set it to 'http://localhost:1234/v1' and this helps.
